FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get dist-upgrade -y
# Install ca-certificate. Required to verify tokens
RUN apt-get install -y ca-certificates golang

# Set default user to a non-root user
RUN useradd -rm -d /home/appuser -s /bin/bash -g users -G sudo -u 1000 appuser
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER appuser