version: '3.0'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    volumes:
      - ./:/home/appuser/jumia
    working_dir: /home/appuser/jumia
    build:
      dockerfile: Dockerfile.local
      context: .
    environment:
      ENV: PROD
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    ports:
      - "8080:8080"
    command: go run .
    links:
      - db
    depends_on:
      - db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    links:
      - db
    depends_on:
      - db
volumes:
  db:
    driver: local